version: 2.1

orbs:
  rn: verypossible-labs/react-native@1.0.0

references:
  # helper method to attach the workspace
  # https://circleci.com/docs/2.0/configuration-reference#attachworkspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: .
  # helper param to persist to the workspace root
  # https://circleci.com/docs/2.0/configuration-reference/#persisttoworkspace
  persist_to_workspace: &persist_workspace
    persist_to_workspace:
      root: .
      paths: .

jobs:
  checkout_code:
    executor:
      name: rn/linux_js
    steps:
      - checkout
      - *persist_workspace

  # all js-related tasks would go in this job
  # e.g. linting and testing
  # note that this is a custom job and is not part of the orb
  analyze_js:
    executor: rn/linux_js
    steps:
      - *attach_workspace
      - rn/yarn_install
      - run:
          name: Run eslint
          command: yarn lint # assumes you have a 'lint' command configuration in the scripts key of your package.json
      - run:
          name: Run unit tests
          command: yarn test # assumes you have a 'test' command configuration in the scripts key of your package.json

  # deploy iOS build to TestFlight via Fastlane
  # note that this is a custom job and is not part of the orb- the steps prefixed with rn/ are commands from the orb that can be used within a job
  deploy_ios_beta:
    executor: rn/macos
    steps:
      - *attach_workspace
      - rn/fastlane:
          platform: ios
          lane: beta # NOTE: this will depend on your fastlane configuration
          description: "Deploy beta app build to TestFlight"

  # deploy iOS build to the App Store via Fastlane
  # note that this is a custom job and is not part of the orb- the steps prefixed with rn/ are commands from the orb that can be used within a job
  deploy_ios_release:
    executor: rn/macos
    steps:
      - *attach_workspace
      - rn/fastlane:
          platform: ios
          lane: release # NOTE: this will depend on your fastlane configuration
          description: "Deploy app release build to the App Store"

  # deploy an Android build to the Google Play Store internal track via Fastlane
  # note that this is a custom job and is not part of the orb- the steps prefixed with rn/ are commands from the orb that can be used within a job
  deploy_android_internal:
    executor: rn/macos
    steps:
      - *attach_workspace
      - rn/fastlane:
          platform: android
          lane: internal # NOTE: this will depend on your fastlane configuration and how you've chosen to setup internal/beta builds in Google Play
          description: "Deploy a beta build to the Google Play Store"

  # deploy an Android build to the Google Play Store via Fastlane
  # note that this is a custom job and is not part of the orb- the steps prefixed with rn/ are commands from the orb that can be used within a job
  deploy_android_release:
    executor: rn/macos
    steps:
      - *attach_workspace
      - rn/fastlane:
          platform: android
          lane: release # NOTE: this will depend on your fastlane configuration
          description: "Deploy a beta build to the Google Play Store"

workflows:
  build_and_deploy:
    jobs:
      - checkout_code

      - analyze_js:
          requires:
            - checkout_code

      # build an iOS release build
      # see src/jobs/ios_build.yml for all parameters
      #
      # note: this job builds and runs e2e tests for iOS. doing this in a single job avoids duplication and spares macOS minutes
      # if you don't want e2e testing, you can use the rn/ios_build job: src/jobs/ios_build.yml which has the same parameters seen here
      - rn/ios_build_and_test:
          name: build_ios_release # a name is required to reference this job in other parts of the config
          project_type: workspace
          project_path: ios/MyApp.xcworkspace
          build_configuration: Release
          device: iPhone 11 Pro
          scheme: MyApp
          node_version: "lts"
          requires:
            - analyze_js
          # to avoid redundancy:
          # we don't run these jobs on staging and main because we can assert that since builds and e2e tests are running on feature branches, that these had to pass through a feature PR branch check already
          # we also assume that our fastlane lane task builds the app, so we don't need to build it again - this may not be the case with your fastlane lane! if not, you will need to add a build task
          filters:
            branches:
              ignore:
                - staging
                - main

      # build an Android release build
      # see src/jobs/android_build for all parameters
      - rn/android_build:
          name: build_android_release # a name is required to reference this job in other parts of the config
          build_type: release
          bundle_type: aab
          requires:
            - analyze_js
          # to avoid redundancy:
          # we don't run these jobs on staging and main because we can assert that since builds and e2e tests are running on feature branches, that these had to pass through a feature PR branch check already
          # we also assume that our fastlane lane task builds the app, so we don't need to build it again - this may not be the case with your fastlane lane! if not, you will need to add a build task
          filters:
            branches:
              ignore:
                - staging
                - main

      # e2e testing on android
      # see: src/jobs/android_test.yml
      - rn/android_test:
          name: android_e2e
          platform_version: android-30
          device_name: MyAppAVD
          requires:
            - build_android_release
          # to avoid redundancy:
          # we don't run these jobs on staging and main because we can assert that since builds and e2e tests are running on feature branches, that these had to pass through a feature PR branch check already
          # we also assume that our fastlane lane task builds the app, so we don't need to build it again - this may not be the case with your fastlane lane! if not, you will need to add a build task
          filters:
            branches:
              ignore:
                - staging
                - main

      - deploy_ios_beta:
          requires:
            - build_ios_release
          # the staging branch should deploy beta builds
          filters:
            branches:
              only:
                - staging

      - deploy_android_internal:
          requires:
            - build_android_release
          # the staging branch should deploy beta builds
          filters:
            branches:
              only:
                - staging

      - deploy_ios_release:
          requires:
            - build_ios_release
          # the main branch should deploy release builds
          filters:
            branches:
              only:
                - main

      - deploy_android_release:
          requires:
            - build_android_release
          # the main branch should deploy release builds
          filters:
            branches:
              only:
                - main
